[book]
authors = ["Anatoly Bugakov"]
language = "en"
multilingual = false
src = "src"
title = "Ultibi Python Pivot Table UI and Cube User Guide(incl FRTB)"
description = "ultibi python user guide: Pivot Table, UI, Cube, FRTB"

[output.html]
default-theme   = "Ayu"
mathjax-support = true
additional-css  = ["tabbed-code-blocks.css"]
additional-js   = ["tabbed-code-blocks.js"]
