[book]
authors = ["Anatoly Bugakov"]
language = "en"
multilingual = false
src = "src"
title = "Ultibi Python FRTB Cube User Guide"
description = "ultibi python developer's user guide. PivotUI, Cube, FRTB."

[output.html]
default-theme   = "Ayu"
mathjax-support = true
additional-css  = ["tabbed-code-blocks.css"]
additional-js   = ["tabbed-code-blocks.js"]
