[book]
authors = ["Anatoly Bugakov"]
language = "en"
multilingual = false
src = "src"
title = "Python FRTB User Guide"
description = "ultibi python developer's frtb user guide. Filtering, overriding, what if."

[output.html]
default-theme   = "Ayu"
mathjax-support = true
additional-css  = ["tabbed-code-blocks.css"]
additional-js   = ["tabbed-code-blocks.js"]
