name: Ultima FRTB Guide

on:
  push:
    branches: [master]

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install static-sitemap-cli
        run: npm install static-sitemap-cli

      - name: Install mdbook
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook
          version: 0.4

      - name: Build book
        run: |
          mdbook build

      - name: Generate sitemap
        run: |
          cd book
          npx sscli --base https://ultibi-frtb-book.github.io
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: book
