name: FRTB User Guide code snippets

on:
  pull_request:
    paths:
      - 'pyultima/**'
      - 'base_engine/**'
      - 'frtb_engine/**'
      - 'frtb_userguide/**'
      - '.github/workflows/test-python-userguide.yaml'
    
defaults:
  run:
    working-directory: frtb_userguide

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: 'frtb_userguide/requirements.txt'

      - name: Create virtual environment
        run: |
          python -m venv venv
          echo "$GITHUB_WORKSPACE/frtb_userguide/venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y graphviz make wget
          pip install -r requirements.txt
          pip install -r requirements-lint.txt
        
      - name: Install Ultima
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run: |
          source activate
          cd ../pyultima
          maturin develop --features=CRR2

      - name: Check formatting
        run: |
          black --check .
          mdformat --check $(find ./src -name "*.md" | grep -v SUMMARY.md)

      - name: Run snippets
        run: |
          make run
